// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgczwmnqxmxusfwapqcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnY3p3bW5xeG14dXNmd2FwcWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzYxOTIsImV4cCI6MjA3MjYxMjE5Mn0.TiUflKd1tsEeevILeZ7zWs93lcEheBuvH4mC_D8m-W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});